### ISSUE TITLE
VM-Exit Transparency Link is Dead 

### ISSUE THREAD

**Issue by bgianfo** [HyperDbg/awesome#1]
It looks like this commit removed that page, so the link should probably be removed from the list.
https://github.com/HyperDbg/research-pages/commit/3f3e06e36e3f9bc4b7a8ac9107d9e0a431db30d3

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating the issue.
It's under final review and will be published in the coming days.

**Comment by SinaKarvandi** [comment]
It's now available.
